"""empty message

Revision ID: 612c4f0df26a
Revises: 7f10b5bb5edb
Create Date: 2019-05-09 16:22:12.073724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612c4f0df26a'
down_revision = '7f10b5bb5edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
