"""empty message

Revision ID: 812506e5971a
Revises: 5701a261ce41
Create Date: 2019-05-25 19:57:05.744477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812506e5971a'
down_revision = '5701a261ce41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('login', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
